### ISSUE TITLE
Favor arrumar o código

### ISSUE THREAD

**Issue by Darkratos** [B1nGh0/SptfAB#1]
Por favor, redija o código de forma mais legível e documentada
para que possamos saber o que está de fato ocorrendo e por que funciona.

**Comment by GH-iPower** [comment]
Eçe codegu num ta legiveu

**Comment by GH-iPower** [comment]
Realmente, este pedaço de software precisa ser redigido pois não consigo entender sua funcionalidade já que foi mal escrito. UP

**Comment by Nomade040** [comment]
+REP +GOD +NOICE

**Comment by B1nGh0** [comment]
Falam sério? Um código de literalmente 56 linhas... onde os nomes das variáveis e funções já seriam autoexplicativos, não sabem o que está ocorrendo? Bom... era de se imaginar que iPower e suas iPowerzettis não conseguiriam entender um código tão simples como esse.

Comentários feitos por GH-iPower e depois deletados por ele mesmo:
"Eçe codegu num ta legiveu"
"Realmente, este pedaço de software precisa ser redigido pois não consigo entender sua funcionalidade já que foi mal escrito. UP"
